paths:
  installation_folder: /home/sr/NetBeansProjects/MirPara4j

model:
  folder: models

rnafold:
  folder: lib
  dll: RNAFold.dll

data:
  folder: data
  data_file: mirbase.dat

program_params:
  prediction_list_size: 100  
  
prediction_params:
  window: 500
  step: 250
  start: 1
  distance: 60
  cutoff: 0.8
  model: "overall"
  level: 1

