/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class no_uio_medisin_bag_jmirpara_MfeFoldRNA */

#ifndef _Included_no_uio_medisin_bag_jmirpara_MfeFoldRNA
#define _Included_no_uio_medisin_bag_jmirpara_MfeFoldRNA
#ifdef __cplusplus
extern "C" {
#endif
#undef no_uio_medisin_bag_jmirpara_MfeFoldRNA_temperature
#define no_uio_medisin_bag_jmirpara_MfeFoldRNA_temperature 37.0f
/*
 * Class:     no_uio_medisin_bag_jmirpara_MfeFoldRNA
 * Method:    fold
 * Signature: (Ljava/lang/String;F)F
 */
JNIEXPORT jfloat JNICALL Java_no_uio_medisin_bag_jmirpara_MfeFoldRNA_fold
  (JNIEnv *, jclass, jstring, jfloat);

/*
 * Class:     no_uio_medisin_bag_jmirpara_MfeFoldRNA
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_no_uio_medisin_bag_jmirpara_MfeFoldRNA_initIDs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
